name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Wait for checks to succeed
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 5
      - uses: actions/checkout@v6
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v5
        with:
          path: .venv
          # same as used in the ci workflow for reuse across workflows
          key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('pyproject.toml') }}
      - if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make install
      - run: make dist
      - name: Publish to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: make publish

  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Wait for checks to succeed
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          interval: 5
      - uses: actions/checkout@v6
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v5
        with:
          path: .venv
          # same as used in the ci workflow for reuse across workflows
          key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-venv-${{ hashFiles('pyproject.toml') }}
      - if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make install
      - name: Test Docker image
        run: uv run pytest integration_tests/test_docker.py
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/gao-artur/fakesnow
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
